# Generated by Django 4.0.4 on 2022-05-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_remove_readingmedia_media_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('notes', models.TextField(max_length=240, verbose_name='notes')),
                ('logtime', models.TimeField()),
                ('characters', models.IntegerField()),
                ('lines', models.IntegerField()),
                ('media_fk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('notes', models.TextField(max_length=240, verbose_name='notes')),
                ('logtime', models.TimeField()),
                ('media_fk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
