# Generated by Django 4.0.4 on 2022-05-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logentry', '0003_alter_listeninglogentry_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninglogentry',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readinglogentry',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
