# Generated by Django 4.0.4 on 2022-05-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logentry', '0004_alter_listeninglogentry_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeninglogentry',
            old_name='logtime',
            new_name='log_time',
        ),
        migrations.RenameField(
            model_name='listeninglogentry',
            old_name='media_fk',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='readinglogentry',
            old_name='logtime',
            new_name='log_time',
        ),
        migrations.RenameField(
            model_name='readinglogentry',
            old_name='media_fk',
            new_name='media',
        ),
    ]
